### ISSUE TITLE
Clarify how to disable background uploads

### ISSUE THREAD

**Issue by Clafou** [ChimeHQ/MeterReporter#2]
The README says:

> To make that easier, you can disable background uploads with another property of MeterReporter.Configuration.

But there is no detail on what that property is, and it took me a bit of digging (into the Wells code) to figure out that to disable background uploads you need to set `backgroundIdentifier = nil` -- maybe making that clearer, at least with a comment for that property, would help!

**Comment by mattmassicotte** [comment]
Ugh, kept your waiting for so long, and for just an annoying issue. Very sorry about that.

Docs updated!
