### ISSUE TITLE
Is there a visualisation tools for Metrics data

### ISSUE THREAD

**Issue by zhouhao27** [ChimeHQ/MeterReporter#5]
The XCode Organizer doesn't show Metrics data when the usage and user count are not enough. I'm able to download Metric payload data through debugging. But the problem is I don't have a tool like XCode Organizer to show the metrics payload in graph. Any idea how to interpret the Metric payload json data? Thanks.

**Comment by mattmassicotte** [comment]
I have a very, very, very rough app that can open MetricKit payloads display call stacks. It does not do visualizations. But, I can open source it.

Again, I want to stress just how rough it is 😅

**Comment by mattmassicotte** [comment]
Here it is: https://github.com/ChimeHQ/MetricKitViewer

It does "work" for crash data. Pull requests very welcome 😃
